/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pokedex;

/**
 *
 * @author Lucas
 */
public class TelaCadastroTreinador extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastroTreinador
     */
    public TelaCadastroTreinador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNomeTreinador = new javax.swing.JTextField();
        txtIdadeTreinador = new javax.swing.JTextField();
        txtCidadeTreinador = new javax.swing.JTextField();
        txtInsigiasTreinador = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 229, 229));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 229, 229));
        jLabel2.setText("Idade:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 229, 229));
        jLabel3.setText("Cidade:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 229, 229));
        jLabel4.setText("Quantidade de Insígnias:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 200, -1));
        getContentPane().add(txtNomeTreinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 133, -1));

        txtIdadeTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadeTreinadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdadeTreinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 137, -1));

        txtCidadeTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeTreinadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtCidadeTreinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 129, -1));
        getContentPane().add(txtInsigiasTreinador, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 53, -1));

        btnCadastrar.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(0, 102, 0));
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.setContentAreaFilled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 180, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/pokedex_img-Photoroom.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // Captura os dados dos campos
    String nomeTreinador = txtNomeTreinador.getText();
    String idadeTreinador = txtIdadeTreinador.getText();
    String cidadeTreinador = txtCidadeTreinador.getText();
    String insigiasTreinador = txtInsigiasTreinador.getText();

    // Exibe os dados no console (aqui você pode salvar ou fazer o que desejar)
    System.out.println("Nome do Treinador: " + nomeTreinador);
    System.out.println("Idade: " + idadeTreinador);
    System.out.println("Cidade: " + cidadeTreinador);
    System.out.println("Quantidade de Insígnias: " + insigiasTreinador);

    // Agora, vamos para a próxima tela: TelaCadastroPokemon
    TelaCadastroPokemon cadastroPokemon = new TelaCadastroPokemon(nomeTreinador, idadeTreinador, cidadeTreinador, insigiasTreinador);
    cadastroPokemon.setVisible(true);
    this.dispose(); // Fecha a tela de cadastro do treinador
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtIdadeTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeTreinadorActionPerformed

    private void txtCidadeTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeTreinadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroTreinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCidadeTreinador;
    private javax.swing.JTextField txtIdadeTreinador;
    private javax.swing.JTextField txtInsigiasTreinador;
    private javax.swing.JTextField txtNomeTreinador;
    // End of variables declaration//GEN-END:variables
}
