/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pokedex;

/**
 *
 * @author Lucas
 */
public class TelaCadastroPokemon extends javax.swing.JFrame {

    private String nomeTreinador;
    private String idadeTreinador;
    private String cidadeTreinador;
    private String insigiasTreinador;
    private java.util.List<Pokemon> pokemons = new java.util.ArrayList<>();
    
    class Pokemon {
    String nome, tipo, nivel;
    Pokemon(String nome, String tipo, String nivel) {
        this.nome = nome;
        this.tipo = tipo;
        this.nivel = nivel;
    }
}
    
    public TelaCadastroPokemon(String nomeTreinador, String idadeTreinador, String cidadeTreinador, String insigiasTreinador) {
        this.nomeTreinador = nomeTreinador;
        this.idadeTreinador = idadeTreinador;
        this.cidadeTreinador = cidadeTreinador;
        this.insigiasTreinador = insigiasTreinador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomePokemon = new javax.swing.JTextField();
        txtTipoPokemon = new javax.swing.JTextField();
        txtNivelPokemon = new javax.swing.JTextField();
        btnOutroPokemon = new javax.swing.JButton();
        btnFinalizarCadastro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Cadastrar pokemon");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, -1, 20));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 231, 231));
        jLabel1.setText("Nome do Pokémon:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 160, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 231, 231));
        jLabel2.setText("Tipo do Pokémon:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 231, 231));
        jLabel3.setText("Nível do Pokémon:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));
        getContentPane().add(txtNomePokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 130, -1));
        getContentPane().add(txtTipoPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 140, -1));

        txtNivelPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNivelPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(txtNivelPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 130, -1));

        btnOutroPokemon.setContentAreaFilled(false);
        btnOutroPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutroPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(btnOutroPokemon, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 560, 40, 40));

        btnFinalizarCadastro.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnFinalizarCadastro.setForeground(new java.awt.Color(0, 102, 0));
        btnFinalizarCadastro.setText("Finalizar cadastro");
        btnFinalizarCadastro.setContentAreaFilled(false);
        btnFinalizarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 700, 180, 90));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resouces/pokedex_img-Photoroom.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutroPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutroPokemonActionPerformed
        // Captura os dados do Pokémon atual
    String nomePokemon = txtNomePokemon.getText();
    String tipoPokemon = txtTipoPokemon.getText();
    String nivelPokemon = txtNivelPokemon.getText();
    
     pokemons.add(new Pokemon(nomePokemon, tipoPokemon, nivelPokemon));
     
     javax.swing.JOptionPane.showMessageDialog(this, "Pokémon cadastrado com sucesso!");

    // Adicione os dados a uma lista ou exiba no console (dependendo do que você deseja fazer)
    System.out.println("Pokémon cadastrado: Nome: " + nomePokemon + ", Tipo: " + tipoPokemon + ", Nível: " + nivelPokemon);

    // Limpa os campos para um novo cadastro
    txtNomePokemon.setText("");
    txtTipoPokemon.setText("");
    txtNivelPokemon.setText("");
    }//GEN-LAST:event_btnOutroPokemonActionPerformed

    private void btnFinalizarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarCadastroActionPerformed
        // Aqui você pode passar todos os dados salvos (como uma lista de Pokémons) para a próxima tela
    TelaResumo telaResumo = new TelaResumo(nomeTreinador, idadeTreinador, cidadeTreinador, insigiasTreinador, pokemons);
    telaResumo.setVisible(true);

    // Fecha a tela atual
    this.dispose();
    }//GEN-LAST:event_btnFinalizarCadastroActionPerformed

    private void txtNivelPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNivelPokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNivelPokemonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            // Exemplo de criação da tela com dados de entrada
            new TelaCadastroPokemon("Ash", "10", "Pallet", "3").setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarCadastro;
    private javax.swing.JButton btnOutroPokemon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtNivelPokemon;
    private javax.swing.JTextField txtNomePokemon;
    private javax.swing.JTextField txtTipoPokemon;
    // End of variables declaration//GEN-END:variables
}
